trigger:
  branches:
    include:
      - main

pr: none

pool: Charlie Agent Pool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azure-infra'
    backendServiceArm: 'charlie service connection'
    backendAzureRmStorageAccountName: 'backendstg10'
    backendAzureRmContainerName: 'backendcnt10'
    backendAzureRmKey: 'nishnat.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-azure-infra'

